# Generated by Django 6.0.5 on 2026-05-19 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastePickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('waste_image', models.ImageField(blank=True, null=True, upload_to='waste_uploads/')),
                ('waste_category', models.CharField(choices=[('PLASTIC', 'Plastic Waste'), ('ORGANIC', 'Organic / Food Waste'), ('E_WASTE', 'Electronic Waste'), ('PAPER', 'Paper & Cardboard'), ('GLASS', 'Glass & Bottles'), ('MIXED', 'Mixed Recyclables')], default='MIXED', max_length=15)),
                ('estimated_volume_m3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('calculated_carbon_offset', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Driver Assigned'), ('IN_TRANSIT', 'Driver in Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('preferred_window', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_tasks', to=settings.AUTH_USER_MODEL)),
                ('pickup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='logistics.wastepickuprequest')),
            ],
        ),
    ]
